import { ThemeInterface } from "./ThemeInterface";

const lightTheme: ThemeInterface = {
  name: "Light",
  type: "light",
  typography: {
    fontSize: "11px",
    menuFontSize: "12px",
    toolbarFontSize: "13px",
  },
  colors: {
    highlight: "#2f6fed",
    highlightText: "#ffffff",
    text: "#1f2833",
    background: "#e7ebf1",
    secondaryText: "#637083",
    token: {
      variable: "#9ccc65",
      character: "#90caf9",
      operator: "#90caf9",
      code: "#aaaaaa",
      function: "#aaaaaa",
      constant: "#90caf9",
    },
    toolbar: {
      background: "linear-gradient(to bottom, #f2f4f8 0%, #dce2ea 100%)",
      border: "#aab5c3",
      inactiveBackground: "#edf1f6",
      inactiveBorder: "#c3ccd8",
      textShadow: "none",
      button: {
        border: "#98a5b8",
      },
    },
    button: {
      background: "linear-gradient(to bottom, #ffffff 0%, #e3e8f0 100%)",
      border: "#9aa7ba",
      activeBackground: "#d3dbe7",
      text: "#1f2833",
      nestedBackground: "#d5dce7",
      nestedActiveBackground: "#c5cedd",
    },
    menu: {
      background: "#ffffff",
      hoverBackground: "#e7edf6",
      activeBackground: "#dce5f2",
      divider: "#c9d2df",
      boxShadow:
        "0 0 0 1px rgba(154, 168, 188, 0.7), 0 12px 24px rgba(32, 41, 54, 0.18)",
    },
    input: {
      background: "#ffffff",
      hoverBackground: "#f5f8fc",
      activeBackground: "#eef3fb",
      text: "#1f2833",
      border: "#b9c6d8",
    },
    brackets: {
      color: "#d0d8e3",
      hoverBackground: "#edf2f8",
    },
    card: {
      background: "#ffffff",
      text: "#1f2833",
      border: "#b8c4d5",
      divider: "#dce3ee",
      boxShadow: "0 10px 22px rgba(37, 47, 61, 0.15)",
    },
    sidebar: {
      background: "#d8dfe8",
      border: "#aeb9c8",
      well: {
        background: "#c7d1df",
        boxShadow: "-1px 0px 10px 0px rgba(38, 48, 60, 0.16) inset",
        hoverBackground: "#b8c4d4",
      },
      header: {
        background: "#eef2f8",
        activeBackground: "#e3e9f2",
        border: "#b6c1d1",
        text: "#1f2833",
      },
    },
    panel: {
      background: "#d9e1eb",
      border: "#afbacb",
      divider: "#bcc7d8",
      text: "#1f2833",
      icon: "#49596d",
      selectedIcon: "#1a2431",
      selectedBackground: "#c2cddc",
      activeBackground: "#cfd8e5",
      hoverBackground: "#d6deea",
    },
    document: {
      background: "#edf2f8",
    },
    list: {
      text: "#1f2833",
      icon: "#6e7e92",
      selectedBackground: "#c3cede",
      activeBackground: "#d2dbe8",
    },
    tabs: {
      background: "linear-gradient(0deg, #d9e0ea 0%, #edf2f8 100%)",
      selectedBackground: "#f6f9fd",
      secondaryBackground: "#e6ecf5",
      border: "#b8c3d4",
    },
    scripting: {
      tabs: {
        background: "#d9e0ea",
      },
      header: {
        text: "#1f2833",
        background: "linear-gradient(0deg, #d3dce8, #e6edf6)",
        nest1Background: "linear-gradient(0deg, #b7d1ea, #c9ddf0)",
        nest2Background: "linear-gradient(0deg, #c5d4ea, #d5e0f1)",
        nest3Background: "linear-gradient(0deg, #c1dbc6, #d2e6d5)",
        nest4Background: "linear-gradient(0deg, #cec1e6, #ddd2f0)",
        commentBackground: "linear-gradient(0deg, #d0deba, #dee8cc)",
        disabledBackground: "linear-gradient(0deg, #e0c6c6, #eddcdc)",
      },
      branch: {
        nest1Background: "#d2e3f2",
        nest2Background: "#d8e2f2",
        nest3Background: "#d7e8d9",
        nest4Background: "#dfd6f1",
      },
      form: {
        background: "#eef3fa",
      },
      children: {
        nest1Border: "#9ec5e4",
        nest1Text: "#2f6fed",
        nest2Border: "#a8bedf",
        nest2Text: "#406fba",
        nest3Border: "#a8cfae",
        nest3Text: "#4d8d59",
        nest4Border: "#b9a9dd",
        nest4Text: "#7153b8",
      },
      placeholder: {
        background: "#d0d8e4",
      },
    },
    tracker: {
      background: "#dde4ee",
      activeBackground: "#cfd8e5",
      border: "#b4c0d1",
      text: "#1f2833",
      note: "#008894",
      instrument: "#738bd7",
      effectCode: "#f45d22",
      effectParam: "#ffad1f",
      rollCell: {
        border: "#1f283366",
      },
    },
    prefab: {
      background: "#2f6fed",
      text: "#ffffff",
      button: {
        background: "#4a83f2",
        hoverBackground: "#5c90f4",
        text: "#ffffff",
      },
    },
    terminal: {
      background: "#ffffff",
      text: "#000000",
      muted: "#6a6a6a",
      border: "#e5e5e5",
      hoverBackground: "#f3f3f3",
      scrollbarTrack: "#f5f5f5",
      scrollbarThumb: "#c1c1c1",
      error: "#cd3131",
      warning: "#bf8803",
      success: "#14ce14",
      debug: "#0451a5",
      system: "#af00db",
      command: "#001080",
      info: "#000000",
      toolbarBackground: "#f3f3f3",
      buttonBackground: "#e5e5e5",
      buttonHover: "#d6d6d6",
      buttonActive: "#007acc",
      inputBackground: "#ffffff",
      prompt: "#14ce14",
      link: "#0066bf",
      linkHover: "#0080ff",
      stackBackground: "#f8f8f8",
      stackText: "#a31515",
    },
  },
  borderRadius: 2,
};

export default lightTheme;
