import type { RPGSettingGroupDefinition } from "./types";

export const RPG_SETTING_GROUPS: RPGSettingGroupDefinition[] = [
  {
    id: "editor-core",
    label: "Editor Core",
    description: "Global editor behavior and workflow defaults.",
    options: [
      {
        id: "autosaveEnabled",
        label: "Autosave Enabled",
        valueType: "boolean",
        defaultValue: true,
        description: "Automatically save project changes in background.",
        functionName: "setAutosaveEnabled(enabled)",
        logic: "When enabled, background save runs on interval and edit checkpoints.",
      },
      {
        id: "autosaveIntervalSec",
        label: "Autosave Interval (sec)",
        valueType: "number",
        defaultValue: 90,
        description: "Time between autosave cycles.",
        functionName: "setAutosaveInterval(seconds)",
        logic: "Lower values increase safety but can increase IO frequency.",
      },
      {
        id: "undoDepth",
        label: "Undo History Depth",
        valueType: "number",
        defaultValue: 200,
        description: "Maximum undo records retained in memory.",
        functionName: "setUndoDepth(count)",
        logic: "Higher depth allows longer undo chains with more memory usage.",
      },
    ],
  },
  {
    id: "viewport-rendering",
    label: "Viewport and Rendering",
    description: "2D viewport quality and draw settings.",
    options: [
      {
        id: "gridVisible",
        label: "Grid Visible",
        valueType: "boolean",
        defaultValue: true,
        description: "Show tile alignment grid in viewport.",
        functionName: "setViewportGridVisible(enabled)",
        logic: "Grid improves placement precision in map editing.",
      },
      {
        id: "snapSize",
        label: "Snap Size",
        valueType: "select",
        defaultValue: 16,
        choices: [8, 16, 32],
        description: "Grid snap size in pixels.",
        functionName: "setViewportSnapSize(size)",
        logic: "Snap size should match target tile resolution.",
      },
      {
        id: "parallaxPreview",
        label: "Parallax Preview",
        valueType: "boolean",
        defaultValue: true,
        description: "Render layered parallax movement preview.",
        functionName: "setParallaxPreviewEnabled(enabled)",
        logic: "Disabling improves performance in heavy scenes.",
      },
    ],
  },
  {
    id: "combat-rules",
    label: "Combat Rules",
    description: "Battle pacing, turn rules, and scaling toggles.",
    options: [
      {
        id: "initiativeMode",
        label: "Initiative Mode",
        valueType: "select",
        defaultValue: "dnd5e",
        choices: ["dnd5e", "speed", "fixed"],
        description: "How combat order is calculated.",
        functionName: "setInitiativeMode(mode)",
        logic: "dnd5e uses d20+dex, speed uses stat-based priority.",
      },
      {
        id: "criticalHitsEnabled",
        label: "Critical Hits Enabled",
        valueType: "boolean",
        defaultValue: true,
        description: "Allow natural critical hit handling.",
        functionName: "setCriticalHitsEnabled(enabled)",
        logic: "When enabled, criticals apply doubled damage dice.",
      },
      {
        id: "encounterScaling",
        label: "Encounter Scaling",
        valueType: "select",
        defaultValue: "party_level",
        choices: ["off", "party_level", "region_tier"],
        description: "Automatic encounter tuning strategy.",
        functionName: "setEncounterScaling(mode)",
        logic: "Scales enemy packs by party level or area tier.",
      },
    ],
  },
  {
    id: "progression-economy",
    label: "Progression and Economy",
    description: "Experience, rewards, and economy balancing.",
    options: [
      {
        id: "xpCurve",
        label: "XP Curve",
        valueType: "select",
        defaultValue: "standard",
        choices: ["slow", "standard", "fast"],
        description: "Leveling progression speed.",
        functionName: "setExperienceCurve(mode)",
        logic: "Affects required XP thresholds by level.",
      },
      {
        id: "lootRandomization",
        label: "Loot Randomization",
        valueType: "boolean",
        defaultValue: true,
        description: "Enable weighted random drop selection.",
        functionName: "setLootRandomizationEnabled(enabled)",
        logic: "When disabled, loot tables resolve deterministically.",
      },
      {
        id: "shopPriceModifier",
        label: "Shop Price Modifier",
        valueType: "number",
        defaultValue: 100,
        description: "Global percent multiplier for shop prices.",
        functionName: "setGlobalShopPriceModifier(percent)",
        logic: "100 means base prices, >100 increases economy difficulty.",
      },
    ],
  },
  {
    id: "world-simulation",
    label: "World Simulation",
    description: "Time/weather and world state simulation options.",
    options: [
      {
        id: "dayNightCycle",
        label: "Day/Night Cycle",
        valueType: "boolean",
        defaultValue: true,
        description: "Enable world time progression.",
        functionName: "setDayNightCycleEnabled(enabled)",
        logic: "Enables time-based events and ambient transitions.",
      },
      {
        id: "weatherSystem",
        label: "Weather System",
        valueType: "select",
        defaultValue: "regional",
        choices: ["off", "global", "regional"],
        description: "Scope of weather simulation updates.",
        functionName: "setWeatherSystemMode(mode)",
        logic: "Regional mode allows different weather per zone.",
      },
      {
        id: "spawnDensity",
        label: "Spawn Density",
        valueType: "number",
        defaultValue: 100,
        description: "Global spawn density percentage.",
        functionName: "setSpawnDensity(percent)",
        logic: "Controls spawn table frequency and world population.",
      },
    ],
  },
  {
    id: "audio",
    label: "Audio and Mixing",
    description: "Music and SFX runtime defaults.",
    options: [
      {
        id: "masterVolume",
        label: "Master Volume",
        valueType: "number",
        defaultValue: 80,
        description: "Master output volume percentage.",
        functionName: "setMasterVolume(percent)",
        logic: "Applies to all buses after per-category scaling.",
      },
      {
        id: "musicVolume",
        label: "Music Volume",
        valueType: "number",
        defaultValue: 75,
        description: "Background music bus volume percentage.",
        functionName: "setMusicVolume(percent)",
        logic: "Used by BGM playback in map and battle scenes.",
      },
      {
        id: "sfxVolume",
        label: "SFX Volume",
        valueType: "number",
        defaultValue: 85,
        description: "Sound effect bus volume percentage.",
        functionName: "setSfxVolume(percent)",
        logic: "Used by UI, world, and battle feedback effects.",
      },
    ],
  },
  {
    id: "build-export",
    label: "Build and Export",
    description: "Compiler and export defaults for target builds.",
    options: [
      {
        id: "targetPlatform",
        label: "Target Platform",
        valueType: "select",
        defaultValue: "gameboy",
        choices: ["gameboy", "web", "desktop"],
        description: "Primary build target profile.",
        functionName: "setTargetPlatform(platform)",
        logic: "Selects export pipeline and output format presets.",
      },
      {
        id: "architectureBitMode",
        label: "Architecture Bit Mode",
        valueType: "select",
        defaultValue: "8bit",
        choices: ["8bit", "16bit", "32bit", "64bit"],
        description: "Selects the runtime architecture profile.",
        functionName: "setArchitectureBitMode(mode)",
        logic: "Controls bit-target assumptions for build and compatibility presets.",
      },
      {
        id: "optimizationLevel",
        label: "Optimization Level",
        valueType: "select",
        defaultValue: "balanced",
        choices: ["debug", "balanced", "size", "speed"],
        description: "Build optimization strategy.",
        functionName: "setBuildOptimization(level)",
        logic: "Controls compiler flags and asset packing policy.",
      },
      {
        id: "includeDebugSymbols",
        label: "Include Debug Symbols",
        valueType: "boolean",
        defaultValue: true,
        description: "Include symbol metadata for debugging.",
        functionName: "setDebugSymbolsEnabled(enabled)",
        logic: "Useful for profiling and stack traces in development.",
      },
    ],
  },
  {
    id: "accessibility",
    label: "Accessibility",
    description: "UI visibility and readability options.",
    options: [
      {
        id: "highContrastUi",
        label: "High Contrast UI",
        valueType: "boolean",
        defaultValue: false,
        description: "Increase contrast ratio in editor surfaces.",
        functionName: "setHighContrastUiEnabled(enabled)",
        logic: "Overrides low-contrast color pairings for readability.",
      },
      {
        id: "colorblindMode",
        label: "Colorblind Mode",
        valueType: "select",
        defaultValue: "off",
        choices: ["off", "protanopia", "deuteranopia", "tritanopia"],
        description: "Apply palette transforms for colorblind support.",
        functionName: "setColorblindMode(mode)",
        logic: "Adjusts accent and alert palette tokens in real-time.",
      },
      {
        id: "uiScale",
        label: "UI Scale",
        valueType: "number",
        defaultValue: 100,
        description: "Editor interface scaling percentage.",
        functionName: "setUiScale(percent)",
        logic: "Scales panel, type, and control dimensions.",
      },
    ],
  },
];

export const RPG_SETTING_GROUP_LABELS = RPG_SETTING_GROUPS.map(
  (group) => group.label,
);

export const RPG_SETTING_OPTION_LABELS = RPG_SETTING_GROUPS.flatMap((group) =>
  group.options.map((option) => `${group.label}: ${option.label}`),
);

export const RPG_SETTING_FUNCTIONS = RPG_SETTING_GROUPS.flatMap((group) =>
  group.options.map((option) => `${group.label}: ${option.functionName}`),
);

export const RPG_SETTING_LOGIC_NOTES = RPG_SETTING_GROUPS.flatMap((group) =>
  group.options.map((option) => `${group.label}: ${option.logic}`),
);
