import type { SciFiEngineSystemInputDefinition } from "./types";

export const SCIFI_ENGINE_SYSTEMS: SciFiEngineSystemInputDefinition[] = [
  {
    id: "space-combat-runtime",
    name: "Space Combat Runtime",
    domain: "combat",
    summary: "Manages weapons, shields, targeting, and hull damage during ship engagements.",
    tools: [
      {
        id: "weapons-fire-controller",
        label: "Weapons Fire Controller",
        category: "runtime",
        description: "Resolves weapon lock-on, firing arcs, and salvo sequences.",
      },
      {
        id: "shield-matrix-manager",
        label: "Shield Matrix Manager",
        category: "runtime",
        description: "Tracks shield facings, recharge rates, and overload states.",
      },
      {
        id: "targeting-computer",
        label: "Targeting Computer",
        category: "runtime",
        description: "Scores targets by threat, distance, and subsystem priority.",
      },
    ],
    functions: [
      "initiateCombat(fleetAId, fleetBId)",
      "lockTarget(shipId, targetId)",
      "fireWeapon(shipId, weaponSlot, targetId)",
      "applyShieldDamage(shipId, facing, amount)",
      "applyHullDamage(shipId, amount)",
      "resolveCountermeasures(shipId)",
      "endCombatEncounter(result)",
    ],
  },
  {
    id: "navigation-runtime",
    name: "Navigation Runtime",
    domain: "navigation",
    summary: "Handles hyperspace jumps, FTL travel, course plotting, and star map queries.",
    tools: [
      {
        id: "hyperspace-plotter",
        label: "Hyperspace Course Plotter",
        category: "runtime",
        description: "Calculates optimal jump routes between star systems.",
      },
      {
        id: "ftl-drive-controller",
        label: "FTL Drive Controller",
        category: "runtime",
        description: "Manages drive charge cycles, cooldowns, and emergency drops.",
      },
    ],
    functions: [
      "plotCourse(originSystemId, destinationSystemId)",
      "initiateHyperspaceJump(shipId, courseId)",
      "dropFromHyperspace(shipId)",
      "scanLocalSpace(shipId, range)",
      "updateStarMap(sectorId)",
      "calculateTravelTime(courseId)",
    ],
  },
  {
    id: "ship-systems-runtime",
    name: "Ship Systems Runtime",
    domain: "systems",
    summary: "Monitors power distribution, life support, hull integrity, and ship subsystems.",
    tools: [
      {
        id: "power-grid-manager",
        label: "Power Grid Manager",
        category: "runtime",
        description: "Allocates reactor output across subsystem demands.",
      },
      {
        id: "life-support-monitor",
        label: "Life Support Monitor",
        category: "runtime",
        description: "Tracks atmosphere, temperature, and oxygen reserves.",
      },
      {
        id: "hull-breach-detector",
        label: "Hull Breach Detector",
        category: "runtime",
        description: "Identifies compromised compartments and routes repair crews.",
      },
    ],
    functions: [
      "setPowerAllocation(systemId, watts)",
      "repairSubsystem(shipId, subsystemId)",
      "sealHullBreach(shipId, compartmentId)",
      "toggleLifeSupport(shipId, active)",
      "overclockReactor(shipId, duration)",
      "runSystemsDiagnostic(shipId)",
    ],
  },
  {
    id: "crew-ai-runtime",
    name: "Crew AI Runtime",
    domain: "crew",
    summary: "Governs crew assignments, morale, skill progression, and behavioral AI.",
    tools: [
      {
        id: "crew-assignment-engine",
        label: "Crew Assignment Engine",
        category: "runtime",
        description: "Matches crew skills to station requirements and shift cycles.",
      },
      {
        id: "morale-simulator",
        label: "Morale Simulator",
        category: "runtime",
        description: "Tracks individual and collective morale modifiers.",
      },
    ],
    functions: [
      "assignCrewToStation(crewId, stationId)",
      "evaluateCrewMorale(crewId)",
      "applyMoraleEvent(eventId, crewIds)",
      "levelUpCrewSkill(crewId, skillId)",
      "fireCrewMember(crewId)",
      "recruitCrewMember(specId, stationId)",
    ],
  },
  {
    id: "research-technology-runtime",
    name: "Research & Technology Runtime",
    domain: "systems",
    summary: "Manages tech tree progression, research point allocation, and technology unlocks.",
    tools: [
      {
        id: "research-queue-manager",
        label: "Research Queue Manager",
        category: "runtime",
        description: "Schedules research tasks and allocates lab capacity.",
      },
      {
        id: "tech-unlock-evaluator",
        label: "Tech Unlock Evaluator",
        category: "runtime",
        description: "Checks prerequisites and triggers technology unlocks.",
      },
    ],
    functions: [
      "startResearch(techId, labId)",
      "cancelResearch(techId)",
      "applyResearchPoints(techId, points)",
      "unlockTechnology(techId)",
      "queryTechPrerequisites(techId)",
      "listAvailableResearch()",
    ],
  },
  {
    id: "faction-diplomacy-runtime",
    name: "Faction & Diplomacy Runtime",
    domain: "systems",
    summary: "Tracks faction allegiances, relation scores, active wars, and treaty negotiations.",
    tools: [
      {
        id: "relation-ledger",
        label: "Relation Ledger",
        category: "runtime",
        description: "Records and adjusts standing scores between factions.",
      },
      {
        id: "treaty-broker",
        label: "Treaty Broker",
        category: "runtime",
        description: "Evaluates treaty terms, acceptance thresholds, and expiry.",
      },
    ],
    functions: [
      "adjustRelation(factionAId, factionBId, delta)",
      "declareWar(factionAId, factionBId)",
      "proposeTreaty(factionAId, factionBId, terms)",
      "acceptTreaty(treatyId)",
      "breakTreaty(treatyId)",
      "queryFactionRelations(factionId)",
    ],
  },
  {
    id: "resource-trade-runtime",
    name: "Resource & Trade Runtime",
    domain: "systems",
    summary: "Handles asteroid mining, cargo management, market prices, and commodity trading.",
    tools: [
      {
        id: "mining-drone-controller",
        label: "Mining Drone Controller",
        category: "runtime",
        description: "Dispatches and recalls mining drones to resource nodes.",
      },
      {
        id: "market-price-engine",
        label: "Market Price Engine",
        category: "runtime",
        description: "Simulates supply/demand curves and trade route effects.",
      },
    ],
    functions: [
      "launchMiningDrone(shipId, asteroidId)",
      "collectMiningYield(droneId)",
      "listMarketOffers(stationId)",
      "purchaseCargo(stationId, commodityId, amount)",
      "sellCargo(stationId, commodityId, amount)",
      "setTradeRoute(shipId, routeId)",
    ],
  },
  {
    id: "mission-contract-runtime",
    name: "Mission & Contract Runtime",
    domain: "systems",
    summary: "Assigns missions, tracks objectives, evaluates completion, and distributes rewards.",
    tools: [
      {
        id: "mission-state-machine",
        label: "Mission State Machine",
        category: "runtime",
        description: "Maintains active, failed, and completed mission states.",
      },
      {
        id: "contract-reward-pipeline",
        label: "Contract Reward Pipeline",
        category: "runtime",
        description: "Distributes credits, reputation, and item rewards on completion.",
      },
    ],
    functions: [
      "acceptMission(missionId)",
      "updateMissionObjective(missionId, objectiveId, progress)",
      "abandonMission(missionId)",
      "completeMission(missionId)",
      "grantMissionRewards(missionId)",
      "listActiveMissions()",
    ],
  },
  {
    id: "galaxy-simulation-runtime",
    name: "Galaxy Simulation Runtime",
    domain: "navigation",
    summary: "Simulates planetary cycles, stellar phenomena, dynamic events, and sector states.",
    tools: [
      {
        id: "stellar-event-generator",
        label: "Stellar Event Generator",
        category: "runtime",
        description: "Spawns supernovae, nebula drifts, and gravitational anomalies.",
      },
      {
        id: "planetary-cycle-clock",
        label: "Planetary Cycle Clock",
        category: "runtime",
        description: "Advances day/season cycles and triggers time-sensitive events.",
      },
    ],
    functions: [
      "tickGalaxyClock(deltaTime)",
      "spawnStellarEvent(eventId, systemId)",
      "despawnStellarEvent(eventId)",
      "updateSectorState(sectorId)",
      "rollRandomEncounter(sectorId)",
      "triggerPlanetaryEvent(planetId, eventId)",
    ],
  },
  {
    id: "save-checkpoint-runtime",
    name: "Save & Checkpoint Runtime",
    domain: "runtime",
    summary: "Serializes full game state, manages save slots, autosave, and version migration.",
    tools: [
      {
        id: "game-state-serializer",
        label: "Game State Serializer",
        category: "runtime",
        description: "Writes full game payload with schema version and checksum.",
      },
      {
        id: "save-migration-assistant",
        label: "Save Migration Assistant",
        category: "runtime",
        description: "Transforms legacy save structures to current schema.",
      },
    ],
    functions: [
      "createSaveSlot(slotId)",
      "writeSave(slotId)",
      "loadSave(slotId)",
      "deleteSave(slotId)",
      "writeAutosave()",
      "migrateSaveData(fromVersion, toVersion)",
    ],
  },
  {
    id: "mod-plugin-runtime",
    name: "Mod & Plugin Runtime",
    domain: "runtime",
    summary: "Loads, validates, and manages mod packages and engine extension hooks.",
    tools: [
      {
        id: "mod-loader",
        label: "Mod Loader",
        category: "runtime",
        description: "Reads mod manifests, resolves dependencies, and loads bundles.",
      },
      {
        id: "hook-registry",
        label: "Hook Registry",
        category: "runtime",
        description: "Registers and dispatches custom engine lifecycle hooks.",
      },
    ],
    functions: [
      "loadMod(modId)",
      "unloadMod(modId)",
      "listLoadedMods()",
      "registerHook(hookName, callback)",
      "validateModManifest(modId)",
      "triggerHook(hookName, payload)",
    ],
  },
  {
    id: "multiplayer-operations-runtime",
    name: "Multiplayer & Operations Runtime",
    domain: "runtime",
    summary: "Supports co-op sessions, server operations, anti-cheat enforcement, and admin tools.",
    tools: [
      {
        id: "session-sync-manager",
        label: "Session Sync Manager",
        category: "runtime",
        description: "Synchronises game state deltas between players and host.",
      },
      {
        id: "anti-cheat-policy-engine",
        label: "Anti-Cheat Policy Engine",
        category: "runtime",
        description: "Evaluates integrity checks and flags suspicious actions.",
      },
    ],
    functions: [
      "createMultiplayerSession(hostId)",
      "joinSession(sessionId, playerId)",
      "leaveSession(playerId)",
      "broadcastStateUpdate(delta)",
      "runAntiCheatScan(playerId)",
      "kickPlayer(playerId, reason)",
      "broadcastAdminMessage(text)",
    ],
  },
];
