import type { RPGSettingsPresetDefinition } from "./types";

export const RPG_SETTINGS_PRESETS: RPGSettingsPresetDefinition[] = [
  {
    id: "balanced-default",
    label: "Balanced Default",
    description: "Stable defaults for mixed development workflows.",
    values: {
      autosaveEnabled: true,
      autosaveIntervalSec: 90,
      undoDepth: 200,
      gridVisible: true,
      snapSize: 16,
      parallaxPreview: true,
      initiativeMode: "dnd5e",
      criticalHitsEnabled: true,
      encounterScaling: "party_level",
      xpCurve: "standard",
      lootRandomization: true,
      shopPriceModifier: 100,
      dayNightCycle: true,
      weatherSystem: "regional",
      spawnDensity: 100,
      masterVolume: 80,
      musicVolume: 75,
      sfxVolume: 85,
      targetPlatform: "gameboy",
      architectureBitMode: "8bit",
      optimizationLevel: "balanced",
      includeDebugSymbols: true,
      highContrastUi: false,
      colorblindMode: "off",
      uiScale: 100,
    },
  },
  {
    id: "combat-lab",
    label: "Combat Lab",
    description: "Fast iteration for battle rules and encounter tuning.",
    values: {
      autosaveEnabled: true,
      autosaveIntervalSec: 45,
      undoDepth: 300,
      gridVisible: true,
      snapSize: 16,
      parallaxPreview: false,
      initiativeMode: "speed",
      criticalHitsEnabled: true,
      encounterScaling: "party_level",
      xpCurve: "fast",
      lootRandomization: false,
      shopPriceModifier: 95,
      dayNightCycle: false,
      weatherSystem: "off",
      spawnDensity: 120,
      masterVolume: 70,
      musicVolume: 55,
      sfxVolume: 95,
      targetPlatform: "desktop",
      architectureBitMode: "32bit",
      optimizationLevel: "debug",
      includeDebugSymbols: true,
      highContrastUi: true,
      colorblindMode: "off",
      uiScale: 105,
    },
  },
  {
    id: "narrative-builder",
    label: "Narrative Builder",
    description: "Optimized for dialogue, quest, and map authoring.",
    values: {
      autosaveEnabled: true,
      autosaveIntervalSec: 60,
      undoDepth: 250,
      gridVisible: false,
      snapSize: 8,
      parallaxPreview: true,
      initiativeMode: "dnd5e",
      criticalHitsEnabled: true,
      encounterScaling: "region_tier",
      xpCurve: "standard",
      lootRandomization: true,
      shopPriceModifier: 100,
      dayNightCycle: true,
      weatherSystem: "regional",
      spawnDensity: 90,
      masterVolume: 75,
      musicVolume: 85,
      sfxVolume: 70,
      targetPlatform: "web",
      architectureBitMode: "16bit",
      optimizationLevel: "balanced",
      includeDebugSymbols: false,
      highContrastUi: false,
      colorblindMode: "deuteranopia",
      uiScale: 110,
    },
  },
];

export const RPG_SETTINGS_PRESET_LABELS = RPG_SETTINGS_PRESETS.map(
  (preset) => preset.label,
);
