export type SciFiTechCategory =
  | "propulsion"
  | "weapons"
  | "defense"
  | "computing"
  | "biology"
  | "energy";

export interface SciFiTechnologyDefinition {
  id: string;
  name: string;
  category: SciFiTechCategory;
  tier: number;
  description: string;
  prerequisites: string[];
  researchCost: number;
  unlocks: string[];
}

export const SCIFI_TECHNOLOGIES: SciFiTechnologyDefinition[] = [
  {
    id: "basic-warp-drive",
    name: "Basic Warp Drive",
    category: "propulsion",
    tier: 1,
    description: "First-generation warp field coils enabling sub-light speed jumps between nearby systems.",
    prerequisites: [],
    researchCost: 500,
    unlocks: ["warp-engine-mk1", "short-range-hyperspace"],
  },
  {
    id: "ftl-hyperdrive",
    name: "FTL Hyperdrive",
    category: "propulsion",
    tier: 2,
    description: "Folded-space hyperdrives that compress travel time across star systems from years to days.",
    prerequisites: ["basic-warp-drive"],
    researchCost: 1500,
    unlocks: ["hyperdrive-mk1", "star-system-navigation"],
  },
  {
    id: "quantum-slipstream",
    name: "Quantum Slipstream Drive",
    category: "propulsion",
    tier: 4,
    description: "Opens a quantum slipstream tunnel for near-instantaneous galactic travel. Extremely energy-intensive.",
    prerequisites: ["ftl-hyperdrive", "quantum-entanglement-comms"],
    researchCost: 8000,
    unlocks: ["slipstream-drive", "cross-sector-navigation"],
  },
  {
    id: "graviton-thrusters",
    name: "Graviton Thrusters",
    category: "propulsion",
    tier: 3,
    description: "Gravitational vectoring thrusters providing superior maneuvering and nullifying inertia penalties.",
    prerequisites: ["ftl-hyperdrive"],
    researchCost: 3000,
    unlocks: ["graviton-drive", "zero-inertia-maneuvering"],
  },
  {
    id: "kinetic-cannons",
    name: "Kinetic Railgun Cannons",
    category: "weapons",
    tier: 1,
    description: "Electromagnetic railguns accelerating solid slugs at hypersonic velocity. Effective against unshielded targets.",
    prerequisites: [],
    researchCost: 400,
    unlocks: ["railgun-mk1", "mass-driver-turret"],
  },
  {
    id: "plasma-weaponry",
    name: "Plasma Weaponry",
    category: "weapons",
    tier: 2,
    description: "Superheated plasma bolts that pierce medium-weight shields and superheat hull plating on impact.",
    prerequisites: ["kinetic-cannons"],
    researchCost: 1200,
    unlocks: ["plasma-cannon", "plasma-torpedo"],
  },
  {
    id: "antimatter-torpedoes",
    name: "Antimatter Torpedoes",
    category: "weapons",
    tier: 4,
    description: "Guided warheads carrying antimatter payloads capable of destroying capital ships in a single salvo.",
    prerequisites: ["plasma-weaponry", "antimatter-containment"],
    researchCost: 9000,
    unlocks: ["antimatter-torpedo-launcher", "siege-warhead"],
  },
  {
    id: "phase-disruptor",
    name: "Phase Disruptor Array",
    category: "weapons",
    tier: 3,
    description: "Fires phase-shifted energy bursts that pass through conventional shields and damage hull directly.",
    prerequisites: ["plasma-weaponry"],
    researchCost: 4500,
    unlocks: ["phase-disruptor-cannon", "shield-bypass-weapon"],
  },
  {
    id: "basic-shields",
    name: "Basic Energy Shields",
    category: "defense",
    tier: 1,
    description: "Electromagnetic deflector fields providing basic protection against energy and kinetic impacts.",
    prerequisites: [],
    researchCost: 600,
    unlocks: ["shield-generator-mk1", "basic-shield-recharge"],
  },
  {
    id: "adaptive-shielding",
    name: "Adaptive Shield Matrix",
    category: "defense",
    tier: 3,
    description: "Shields that dynamically tune frequency in response to incoming weapon signatures, increasing resistance.",
    prerequisites: ["basic-shields"],
    researchCost: 3500,
    unlocks: ["adaptive-shield-generator", "shield-frequency-analyser"],
  },
  {
    id: "ablative-hull-plating",
    name: "Ablative Hull Plating",
    category: "defense",
    tier: 2,
    description: "Sacrificial hull layers that vaporise on impact, absorbing and dispersing destructive energy.",
    prerequisites: ["basic-shields"],
    researchCost: 1800,
    unlocks: ["ablative-armor-mk1", "compartment-isolation-bulkheads"],
  },
  {
    id: "nano-repair-systems",
    name: "Nanite Repair Systems",
    category: "defense",
    tier: 3,
    description: "Swarms of repair nanites that autonomously patch hull breaches and restore system integrity in combat.",
    prerequisites: ["ablative-hull-plating", "nano-fabrication"],
    researchCost: 5000,
    unlocks: ["hull-nanite-swarm", "auto-repair-module"],
  },
  {
    id: "quantum-ai",
    name: "Quantum AI Core",
    category: "computing",
    tier: 3,
    description: "Quantum-state processors enabling true machine consciousness and real-time fleet-scale tactical calculations.",
    prerequisites: ["neural-computing"],
    researchCost: 6000,
    unlocks: ["quantum-ai-bridge", "autonomous-fleet-control"],
  },
  {
    id: "neural-computing",
    name: "Neural Computing Networks",
    category: "computing",
    tier: 2,
    description: "Brain-inspired computing architectures with exponentially higher bandwidth than conventional processors.",
    prerequisites: [],
    researchCost: 2000,
    unlocks: ["neural-nav-computer", "enhanced-targeting-ai"],
  },
  {
    id: "quantum-entanglement-comms",
    name: "Quantum Entanglement Comms",
    category: "computing",
    tier: 3,
    description: "Instantaneous FTL communication via entangled particle pairs, immune to jamming or interception.",
    prerequisites: ["neural-computing"],
    researchCost: 4000,
    unlocks: ["qe-comm-array", "fleet-tactical-network"],
  },
  {
    id: "genetic-augmentation",
    name: "Genetic Crew Augmentation",
    category: "biology",
    tier: 2,
    description: "Approved genetic therapies boosting crew endurance, reaction speed, and vacuum survival tolerance.",
    prerequisites: [],
    researchCost: 2500,
    unlocks: ["aug-crew-trait-resilient", "aug-crew-trait-swift"],
  },
  {
    id: "cybernetic-implants",
    name: "Combat Cybernetic Implants",
    category: "biology",
    tier: 3,
    description: "Neural and skeletal cybernetic enhancements that enable direct interface with ship systems and augmented combat performance.",
    prerequisites: ["genetic-augmentation"],
    researchCost: 4500,
    unlocks: ["neural-interface-implant", "combat-reflex-implant"],
  },
  {
    id: "nano-fabrication",
    name: "Nano-Fabrication",
    category: "biology",
    tier: 2,
    description: "Molecular-scale manufacturing that assembles complex materials and components from raw feedstocks.",
    prerequisites: [],
    researchCost: 3000,
    unlocks: ["nano-fab-bay", "advanced-material-synthesis"],
  },
  {
    id: "antimatter-containment",
    name: "Antimatter Containment Fields",
    category: "energy",
    tier: 3,
    description: "Stable magnetic bottles that safely contain and store antimatter for use in weapons and drive systems.",
    prerequisites: ["zero-point-energy"],
    researchCost: 5500,
    unlocks: ["antimatter-reactor", "antimatter-fuel-storage"],
  },
  {
    id: "zero-point-energy",
    name: "Zero-Point Energy Tapping",
    category: "energy",
    tier: 2,
    description: "Extracts energy from quantum vacuum fluctuations, providing near-limitless supplemental power generation.",
    prerequisites: [],
    researchCost: 3500,
    unlocks: ["zpe-reactor-module", "power-surplus-shield-boost"],
  },
  {
    id: "fusion-reactor",
    name: "Compact Fusion Reactor",
    category: "energy",
    tier: 1,
    description: "Miniaturised fusion plants delivering reliable high-density power output for ship systems and weapons.",
    prerequisites: [],
    researchCost: 800,
    unlocks: ["fusion-reactor-mk1", "power-grid-expansion"],
  },
  {
    id: "dyson-harvesting",
    name: "Stellar Energy Harvesting",
    category: "energy",
    tier: 4,
    description: "Micro-scale Dyson collector arrays placed in stellar orbits to harvest vast amounts of solar energy.",
    prerequisites: ["zero-point-energy", "quantum-slipstream"],
    researchCost: 12000,
    unlocks: ["stellar-collector-array", "unlimited-power-bonus"],
  },
];
